include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false 
    unused_import : ignore
    prefer_interpolation_to_compose_strings : false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    constant_identifier_names : false

