name: finance
description: The fundamental package for financial computing with Dart.
version: 0.1.1
homepage: https://github.com/ismaelJimenez/finance

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.4.2
  test: ^1.24.3
